Use system ansible and python, work around asdf plugin add issue

diff --git a/update b/update
--- a/update
+++ b/update
@@ -45,12 +45,15 @@ if [ "${DOTFILES_DEV}" == "y"  ]; then
 fi
 
 if [ ${#playbooks[@]} -gt 0 ]; then
-  ansible-playbook --ask-become-pass -e ansible_python_interpreter=/usr/bin/python3 \
+  PATH=/usr/bin:/bin ansible-playbook --ask-become-pass -e ansible_python_interpreter=/usr/bin/python3 \
     $(IFS=" " ;echo "${playbooks[*]}")
 fi
 
 # Install asdf plugins
+set +e # This is a bad hack to get around this command failing when all plugins are installed
 awk '{print $1}' ~/.tool-versions | xargs -L1 asdf plugin-add
+set -e
+
 asdf install
 
 update_vim
